"""create initial schema

Revision ID: 2f29fa23597c
Revises: 
Create Date: 2026-07-30 10:34:19.707677

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2f29fa23597c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='카테고리 ID 일련번호'),
    sa.Column('category_name', sa.String(length=100), nullable=False, comment='카테고리명'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='화면 노출 순서'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='사용 여부'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='상위 카테고리 ID'),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.category_id'], name=op.f('fk_categories_parent_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_categories')),
    sa.UniqueConstraint('category_name', name='uq_categories_category_name'),
    comment='카테고리'
    )
    op.create_index('ix_categories_parent_id_is_active_sort_order', 'categories', ['parent_id', 'is_active', 'sort_order'], unique=False)
    op.create_table('trends',
    sa.Column('trend_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='트렌드 정보 ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='사용자에게 표시할 트렌드 제목'),
    sa.Column('normalized_title', sa.String(length=255), nullable=False, comment='중복 비교용 정규화 트렌드 제목'),
    sa.Column('summary', sa.Text(), nullable=True, comment='기본 요약'),
    sa.Column('thumbnail_url', sa.Text(), nullable=True, comment='대표 이미지 URL'),
    sa.Column('status', sa.Enum('ACTIVE', 'HIDDEN', name='trend_status'), server_default='ACTIVE', nullable=False, comment='조회 가능 상태'),
    sa.Column('first_collected_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='최초 수집 시각'),
    sa.Column('last_collected_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='마지막 수집 시각'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정 시각'),
    sa.PrimaryKeyConstraint('trend_id', name=op.f('pk_trends')),
    sa.UniqueConstraint('normalized_title', name='uq_trends_normalized_title'),
    comment='트렌드 정보'
    )
    op.create_index('ix_trends_status_last_collected_at', 'trends', ['status', 'last_collected_at'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='사용자 ID 일련번호'),
    sa.Column('login_id', sa.String(length=50), nullable=True, comment='로그인 ID'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='비밀번호 해시값'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='사용자 이름'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='이메일 & OAuth 연동'),
    sa.Column('status', sa.Enum('ACTIVE', 'WITHDRAWN', 'SUSPENDED', name='user_status'), server_default='ACTIVE', nullable=False, comment='계정 상태'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='사용자 가입 시각'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='계정 수정 시각'),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True, comment='탈퇴 시각'),
    sa.Column('withdraw_reason', sa.String(length=255), nullable=True, comment='회원 탈퇴 사유'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('login_id', name='uq_users_login_id'),
    comment='사용자'
    )
    op.create_table('oauth_accounts',
    sa.Column('oauth_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='OAuth 계정 ID 일련번호'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='사용자 ID'),
    sa.Column('provider', sa.Enum('GOOGLE', name='oauth_provider'), server_default='GOOGLE', nullable=False, comment='정보 제공자'),
    sa.Column('provider_user_id', sa.String(length=100), nullable=False, comment='외부 서비스 사용자 식별값'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='OAuth 이메일'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='OAuth 계정 연동 시각'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_oauth_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oauth_id', name=op.f('pk_oauth_accounts')),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_accounts_provider_provider_user_id'),
    comment='OAuth 계정'
    )
    op.create_table('search_logs',
    sa.Column('search_log_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='검색 기록 ID 일련번호'),
    sa.Column('keyword', sa.String(length=255), nullable=False, comment='사용자가 입력한 검색어 원문'),
    sa.Column('normalized_keyword', sa.String(length=255), nullable=False, comment='중복 비교용 정규화 검색어'),
    sa.Column('result_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='검색 결과 건수'),
    sa.Column('searched_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='검색 실행 시각'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='검색을 실행한 사용자 ID'),
    sa.Column('category_id', sa.BigInteger(), nullable=True, comment='검색 시 적용한 카테고리 ID'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_search_logs_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_search_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('search_log_id', name=op.f('pk_search_logs')),
    sa.UniqueConstraint('user_id', 'normalized_keyword', name='uq_search_logs_user_id_normalized_keyword'),
    comment='사용자별 최근 검색어'
    )
    op.create_index('ix_search_logs_user_id_searched_at', 'search_logs', ['user_id', 'searched_at'], unique=False)
    op.create_table('trend_ai_analyses',
    sa.Column('analysis_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='AI 분석 ID 일련번호'),
    sa.Column('analysis_version', sa.Integer(), nullable=False, comment='트렌드별 AI 분석 버전'),
    sa.Column('one_line_summary', sa.String(length=500), nullable=False, comment='AI 한줄 요약'),
    sa.Column('reason_text', sa.Text(), nullable=False, comment='유행 이유 설명'),
    sa.Column('detail_text', sa.Text(), nullable=True, comment='상세 설명'),
    sa.Column('model_provider', sa.String(length=30), nullable=False, comment='AI 모델 제공자'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='사용 AI 모델명'),
    sa.Column('prompt_version', sa.String(length=30), nullable=False, comment='분석 프롬프트 버전'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='AI 분석 생성 시각'),
    sa.Column('trend_id', sa.BigInteger(), nullable=False, comment='트렌드 정보 ID'),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.trend_id'], name=op.f('fk_trend_ai_analyses_trend_id_trends'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id', name=op.f('pk_trend_ai_analyses')),
    sa.UniqueConstraint('trend_id', 'analysis_version', name='uq_trend_ai_analyses_trend_id_analysis_version'),
    comment='트렌드 AI 분석'
    )
    op.create_table('trend_category_map',
    sa.Column('trend_category_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='트렌드 카테고리 매핑 ID 일련번호'),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='대표 카테고리 여부'),
    sa.Column('category_id', sa.BigInteger(), nullable=False, comment='카테고리 ID'),
    sa.Column('trend_id', sa.BigInteger(), nullable=False, comment='트렌드 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='카테고리 연결 시각'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_trend_category_map_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.trend_id'], name=op.f('fk_trend_category_map_trend_id_trends'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trend_category_id', name=op.f('pk_trend_category_map')),
    sa.UniqueConstraint('trend_id', 'category_id', name='uq_trend_category_map_trend_id_category_id'),
    comment='트렌드-카테고리 매핑 테이블'
    )
    op.create_index('ix_trend_category_map_category_id_trend_id', 'trend_category_map', ['category_id', 'trend_id'], unique=False)
    op.create_table('trend_rank_snapshots',
    sa.Column('rank_snapshot_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='순위 기록 ID 일련번호'),
    sa.Column('platform', sa.Enum('GOOGLE', 'YOUTUBE', 'SNS', 'ETC', name='trend_rank_platform', native_enum=False, length=30), nullable=False, comment='순위 기준 플랫폼'),
    sa.Column('ranking', sa.Integer(), nullable=False, comment='수집 시점의 플랫폼 순위'),
    sa.Column('rank_delta', sa.Integer(), nullable=True, comment='직전 순위 대비 순위 변동값'),
    sa.Column('score', sa.Numeric(precision=12, scale=4), nullable=True, comment='플랫폼에서 제공한 트렌드 점수'),
    sa.Column('snapshot_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='스냅샷 시각'),
    sa.Column('trend_id', sa.BigInteger(), nullable=False, comment='트렌드 정보 ID'),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.trend_id'], name=op.f('fk_trend_rank_snapshots_trend_id_trends'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rank_snapshot_id', name=op.f('pk_trend_rank_snapshots')),
    sa.UniqueConstraint('trend_id', 'platform', 'snapshot_at', name='uq_trend_rank_snapshots_trend_id_platform_snapshot_at'),
    comment='트렌드 순위 스냅샷'
    )
    op.create_index('ix_trend_rank_snapshots_platform_snapshot_at_ranking', 'trend_rank_snapshots', ['platform', 'snapshot_at', 'ranking'], unique=False)
    op.create_index('ix_trend_rank_snapshots_trend_id_snapshot_at', 'trend_rank_snapshots', ['trend_id', 'snapshot_at'], unique=False)
    op.create_table('trend_sources',
    sa.Column('source_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='출처 ID 일련번호'),
    sa.Column('source_key', sa.CHAR(length=64), nullable=False, comment='중복 비교용 출처 SHA-256 해시값'),
    sa.Column('source_url', sa.Text(), nullable=False, comment='원문 또는 수집 URL'),
    sa.Column('source_title', sa.String(length=255), nullable=True, comment='수집 자료 제목'),
    sa.Column('platform', sa.Enum('GOOGLE', 'YOUTUBE', 'SNS', 'ETC', name='trend_source_platform', native_enum=False, length=30), nullable=False, comment='수집 플랫폼'),
    sa.Column('collected_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='수집 시각'),
    sa.Column('external_id', sa.String(length=255), nullable=True, comment='외부 플랫폼 사용자 또는 콘텐츠 식별값'),
    sa.Column('trend_id', sa.BigInteger(), nullable=False, comment='트렌드 정보 ID'),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.trend_id'], name=op.f('fk_trend_sources_trend_id_trends'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_trend_sources')),
    sa.UniqueConstraint('trend_id', 'source_key', name='uq_trend_sources_trend_source_key'),
    comment='트렌드 출처 정보 저장'
    )
    op.create_table('user_interest_categories',
    sa.Column('user_interest_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='사용자 관심사 ID 일련번호'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='사용자 ID'),
    sa.Column('category_id', sa.BigInteger(), nullable=False, comment='카테고리 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='관심 카테고리 선택 시각'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_user_interest_categories_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_user_interest_categories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_interest_id', name=op.f('pk_user_interest_categories')),
    sa.UniqueConstraint('user_id', 'category_id', name='uq_user_interest_categories_user_id_category_id'),
    comment='사용자 관심사 카테고리'
    )
    op.create_table('user_profiles',
    sa.Column('profile_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='프로필 ID 일련번호'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='사용자 ID'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='화면 표시용 닉네임'),
    sa.Column('profile_image_url', sa.Text(), nullable=True, comment='프로필 이미지 경로'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정 시각'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name='uq_user_profiles_user_id'),
    comment='사용자 프로필'
    )
    op.create_table('user_trend_bookmarks',
    sa.Column('bookmark_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='북마크 ID 일련번호'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='북마크 생성 시각'),
    sa.Column('trend_id', sa.BigInteger(), nullable=False, comment='트렌드 정보 ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='사용자 ID'),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.trend_id'], name=op.f('fk_user_trend_bookmarks_trend_id_trends'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_user_trend_bookmarks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bookmark_id', name=op.f('pk_user_trend_bookmarks')),
    sa.UniqueConstraint('user_id', 'trend_id', name='uq_user_trend_bookmarks_user_id_trend_id'),
    comment='사용자 저장 트렌드'
    )
    op.create_index('ix_user_trend_bookmarks_user_id_created_at', 'user_trend_bookmarks', ['user_id', 'created_at'], unique=False)
    op.create_table('trend_related_keywords',
    sa.Column('related_keyword_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='관련 키워드 ID 일련번호'),
    sa.Column('keyword', sa.String(length=100), nullable=False, comment='키워드 이름'),
    sa.Column('normalized_keyword', sa.String(length=100), nullable=False, comment='중복 비교용 정규화 키워드'),
    sa.Column('keyword_type', sa.Enum('RELATED', 'HASHTAG', 'RECOMMENDED', name='related_keyword_type'), server_default='RELATED', nullable=False, comment='관련 키워드 유형'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='표시 순서'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='관련 키워드 생성 시각'),
    sa.Column('analysis_id', sa.BigInteger(), nullable=False, comment='AI 분석 ID'),
    sa.ForeignKeyConstraint(['analysis_id'], ['trend_ai_analyses.analysis_id'], name=op.f('fk_trend_related_keywords_analysis_id_trend_ai_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('related_keyword_id', name=op.f('pk_trend_related_keywords')),
    sa.UniqueConstraint('analysis_id', 'normalized_keyword', name='uq_trend_related_keywords_analysis_id_normalized_keyword'),
    comment='AI 분석 관련 키워드'
    )
    op.create_index('ix_trend_related_keywords_analysis_id_keyword_type_sort_order', 'trend_related_keywords', ['analysis_id', 'keyword_type', 'sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # 자식 테이블부터 부모 테이블 순서로 삭제한다.
    # 테이블 삭제 시 해당 테이블의 인덱스와 제약조건도 함께 삭제된다.
    op.drop_table("trend_related_keywords")
    op.drop_table("user_trend_bookmarks")
    op.drop_table("user_profiles")
    op.drop_table("user_interest_categories")
    op.drop_table("trend_sources")
    op.drop_table("trend_rank_snapshots")
    op.drop_table("trend_category_map")
    op.drop_table("trend_ai_analyses")
    op.drop_table("search_logs")
    op.drop_table("oauth_accounts")
    op.drop_table("users")
    op.drop_table("trends")
    op.drop_table("categories")
    # ### end Alembic commands ###