"""add category code

Revision ID: 7e9d740c5df1
Revises: 2f29fa23597c
Create Date: 2026-08-03 15:19:07.959019

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '7e9d740c5df1'
down_revision: Union[str, Sequence[str], None] = '2f29fa23597c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_code', sa.Enum('FASHION', 'FOOD', 'IT_DIGITAL', 'ENTERTAINMENT', 'BEAUTY', 'GAME', name='category_code'), nullable=True, comment='카테고리 코드'))
    op.create_unique_constraint('uq_categories_category_code', 'categories', ['category_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_categories_category_code', 'categories', type_='unique')
    op.drop_column('categories', 'category_code')
    # ### end Alembic commands ###